backend:
  name: github
  repo: polacyrodacy/Main
  branch: main

media_folder: "assets/images"   # gdzie zapisujesz obrazki
public_folder: "/assets/images"

collections:
  - name: "news"
    label: "News"
    folder: "Main/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Obrazek", name: "image", widget: "image" }
      - { label: "Treść", name: "body", widget: "markdown" }
