backend:
  name: github
  repo: polacyrodacy/polacyrodacy  # Twój prawdziwy repozytorium
  branch: main

media_folder: "assets/images"  # gdzie trafiają obrazki (lokalnie)
public_folder: "/assets/images"  # jak będą widoczne na stronie

collections:
  - name: "news"
    label: "News"
    folder: "news"  # tu masz już pliki .md
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Data publikacji", name: "date", widget: "datetime" }
      - { label: "Treść", name: "body", widget: "markdown" }  # WYSIWYG edytor